### ISSUE TITLE
The field customProperties[property=owner].value is not set. Please specify a team ID for the owner of the data contract.

### ISSUE THREAD

**Issue by struesda** [datacontract-manager/datacontract-manager-ce#4]
![Image](https://github.com/user-attachments/assets/9b7baac1-81ca-44bb-964d-12f93d6e4915)

When I enter valid ODCS YAML to create a new data contract I get this error.

Where it expecting to find this custom property?

**Comment by glalanne** [comment]
I had the same issue, and it seems that the application is mandating those extra custom properties to fit into the previous data model.

Just add the required missing field and you should be good
```yaml 
apiVersion: v3.0.2
kind: DataContract

customProperties:
- property: owner
  value: platform-team
```
