### ISSUE TITLE
49 rows limits in Excel Export for ODCS DataContract with multiple schema and columns

### ISSUE THREAD

**Issue by dmaresma** [datacontract-manager/datacontract-manager-ce#5]
Data Contract (ODCS spécification) with more than 49 attributes the excel template doesn't support the 50th and follow attributes.

```
kind: DataContract
id: mba.internal.snowflake.KLD
name: MBA.KLD
version: 0.0.1
domain: b2b, delivery
status: active
customProperties:
  - property: owner
    value: dataplatform
servers:
  - server : workspace_qa
    type: snowflake
    description: snowflake workspace mcKesson canada
    environment: prd
    host: mckesson.canada-central.azure.snowflakecomputing.com
    port: 443
    account: mckesson.canada-central
    database: QA_ENT_DL_DATALAKE_CA
    warehouse: LOAD_WH
    schema: MBA_DATA_SRC
    roles:
      - role: QA_ENT_DW_ENGINEER_FR
        access: write
        firstLevelApprovers: Darlene Demchuk (mailto:darlene.demchuk@mckesson.ca)
        secondLevelApprovers: Phuong Dao (mailto:phuong.dao@mckesson.ca)
  - server : workspace_prd
    type: snowflake
    description: snowflake workspace mcKesson canada
    environment: prd
    host: mckesson.canada-central.azure.snowflakecomputing.com
    port: 443
    account: mckesson.canada-central
    database: PRD_ENT_DL_DATALAKE_CA
    warehouse: LOAD_WH
    schema: MBA_DATA_SRC
    roles:
      - role: PRD_ENT_DW_ENGINEER_FR
        access: write
        firstLevelApprovers: Darlene Demchuk (mailto:darlene.demchuk@mckesson.ca)
        secondLevelApprovers: Phuong Dao (mailto:phuong.dao@mckesson.ca)
slaDefaultElement: MBA_DATA_SRC 
slaProperties:
  - property: latency 
    value: 4
    unit: d 
    element: MBA_DATA_SRC 
  - property: generalAvailability
    value: 2025-02-28T09:30:10-08:00
  - property: endOfSupport
    value: 2065-02-12T09:30:10-08:00
  - property: endOfLife
    value: 2099-12-31T09:30:10-08:00
  - property: retention
    value: 99
    unit: y
  - property: frequency
    value: 1
    valueExt: 1
    unit: d
  - property: timeOfAvailability
    value: 09:00-23:59
    driver: regulatory 
  - property: timeOfAvailability
    value: 09:00-23:59
    driver: analytics 
team:
  - username: Alf
    role: Data Engineer
    dateIn: 2025-01-06
  - username: Damien
    role: Data Architect
    dateIn: 2023-06-04
  - username: Darlene
    role: Owner
    comment: Keeper of the grail
    name: Darlene Demchuk
    dateIn: 2024-03-01
support:
  - channel: DataHub Support
    tool: teams
    scope: interactive
    url: https://teams.microsoft.com/l/channel/19%3Af61656c235944861afc3d057f79976a1%40thread.skype/%F0%9F%92%81Support?groupId=cee15c75-5829-4682-b99f-df4373693b96&tenantId=da67ef1b-ca59-4db2-9a8c-aa8d94617a16
  - channel: MEP
    tool: teams
    scope: announcements
    url: https://teams.microsoft.com/l/channel/19%3A2d858f28cded490a8a863732818f3b2c%40thread.skype/%E2%80%BC%EF%B8%8FMEP?groupId=cee15c75-5829-4682-b99f-df4373693b96&tenantId=da67ef1b-ca59-4db2-9a8c-aa8d94617a16
  - channel: DataContract Change
    description: All announcement for all data contracts
    tool: teams
    scope: announcements
    url: https://bitol.io/teams/channel/all-announcements
  - channel: Legacy
    tool: email
    scope: announcements
    url: mailto:dh_canada@mckesson.ca
  - channel: Jira
    tool: ticket
    url: https://mckesson.atlassian.net/jira/software/c/projects/CANDAA/boards/4080
schema:
- name: CTRANEG
  physicalName: MDA_DATA_SRC.CTRANEG
  logicalType: object
  physicalType: table
  tags: []
  properties:
  - name: APP_NAME
    logicalType: string
    physicalType: string
    required: true
    unique: false
    description : Application process that last Created or Updated the record.
    logicalTypeOptions:
      maxLength: 16777216
  - name: CREATE_TS
    logicalType: date
    physicalType: timestamp_ntz
    required: true
    unique: false
    description : Audit timestamp that the record was initially Created.
  - name: CREATE_AUDIT_ID
    logicalType: number
    physicalType: decimal
    required: true
    unique: false
    description : Identifier generated by the load process that initially Created the record.
  - name: UPDATE_TS
    logicalType: date
    physicalType: timestamp_ntz
    required: true
    unique: false
    description: Audit timestamp that the record was last Updated.
  - name: UPDATE_AUDIT_ID
    logicalType: number
    physicalType: decimal
    required: true
    unique: false
    description: Identifier generated by the load process that last Updated the record.
  - name: CURRENT_RECORD_IND
    logicalType: boolean
    physicalType: boolean
    required: true
    unique: false
    description: SCD Type 2 the current record is true otherwise false. SCD other - true by default
  - name: DELETED_RECORD_IND
    logicalType: boolean
    physicalType: boolean
    required: true
    unique: false
    description: If a record that has been removed from the source (soft deleted) is true
  - name: FILE_BLOB_PATH
    logicalType: string
    physicalType: string
    required: true
    unique: false
    description: Required when is already in DL
    logicalTypeOptions:
      maxLength: 16777216
  - name: FILE_ROW_NUMBER
    logicalType: string
    physicalType: string
    required: true
    unique: false
    logicalTypeOptions:
      maxLength: 16777216
  - name: FILE_LAST_MODIFIED
    logicalType: string
    physicalType: string
    required: true
    unique: false
    logicalTypeOptions:
      maxLength: 16777216
  - name: CTRANEG_SK
    logicalType: number
    physicalType: decimal
    required: true
    unique: false
  - name: CCDIV
    logicalType: string
    description: CODE DIVISION
    required: true
    physicalType: CHAR(3)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CCDIV
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CNPRD
    logicalType: number
    description: NO PRODUIT
    required: true
    physicalType: DECIMAL(6,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CNPRD
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CCBANC
    logicalType: string
    description: CODE BANNIERE DU CONTRAT
    required: true
    physicalType: CHAR(3)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CCBANC
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CDTDEB
    logicalType: number
    description: DATE DEBUT
    required: true
    physicalType: DECIMAL(8,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CDTDEB
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CDTFIN
    logicalType: number
    description: DATE FIN
    required: true
    physicalType: DECIMAL(8,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CDTFIN
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CDTMAJ
    logicalType: number
    description: DATE MAJ DU RECORD CRE/MODIF
    required: true
    physicalType: DECIMAL(8,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CDTMAJ
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CFIL01
    logicalType: number
    description: None
    required: true
    physicalType: DECIMAL(7,3)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CFIL01
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CFIL02
    logicalType: number
    description: None
    required: true
    physicalType: DECIMAL(8,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CFIL02
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CQTOT
    logicalType: number
    description: QTE TOTALE
    required: true
    physicalType: DECIMAL(6,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CQTOT
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CQCOM
    logicalType: number
    description: QTE SOUS COMMANDE
    required: true
    physicalType: DECIMAL(6,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CQCOM
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CQBOF
    logicalType: number
    description: QTE BO FOURNISSEUR
    required: true
    physicalType: DECIMAL(6,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CQBOF
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CQBOC
    logicalType: number
    description: QTE BO CLIENTS
    required: true
    physicalType: DECIMAL(6,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CQBOC
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CQPRA
    logicalType: number
    description: QTE RECUE PRA
    required: true
    physicalType: DECIMAL(6,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CQPRA
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CNBON
    logicalType: number
    description: NO BON RECU PRA
    required: true
    physicalType: DECIMAL(5,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CNBON
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CDTREC
    logicalType: number
    description: DATE RECEPTION DU BON PRA
    required: true
    physicalType: DECIMAL(8,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CDTREC
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CDTDCM
    logicalType: number
    description: DATE DERNIERE COMMANDE
    required: true
    physicalType: DECIMAL(8,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CDTDCM
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CDTDRC
    logicalType: number
    description: DATE DERNIERE RECEPTION
    required: true
    physicalType: DECIMAL(8,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CDTDRC
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CNCTRA
    logicalType: number
    description: NO CONTRAT SEQ. INTERNE
    required: true
    physicalType: NUMERIC(5,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CNCTRA
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CRCTRA
    logicalType: string
    description: NO REFERENCE CONTRAT
    required: true
    physicalType: CHAR(10)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CRCTRA
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CTAUX
    logicalType: number
    description: TAUX CALCULANT LE VENDANT
    required: true
    physicalType: DECIMAL(4,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CTAUX
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CFIL03
    logicalType: number
    description: None
    required: true
    physicalType: DECIMAL(8,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CFIL03
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CCPROV
    logicalType: string
    description: CODE DE PROVENANCE R = RECEPTION C = CREDIT A = AJ
    required: true
    physicalType: CHAR(1)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CCPROV
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CNPRM
    logicalType: number
    description: NO PROMO-CONTRAT
    required: true
    physicalType: NUMERIC(5,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CNPRM
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CFIL04
    logicalType: number
    description: None
    required: true
    physicalType: DECIMAL(8,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CFIL04
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CFIL05
    logicalType: number
    description: None
    required: true
    physicalType: DECIMAL(8,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CFIL05
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CCRBVL
    logicalType: string
    description: CODE RABAIS VOLUME
    required: true
    physicalType: CHAR(1)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CCRBVL
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CQVEND
    logicalType: number
    description: QTE VENDUE UNITES A DATE
    required: true
    physicalType: DECIMAL(8,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CQVEND
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CVENDQ
    logicalType: number
    description: QTE VENDUE UNITES DU MOIS
    required: true
    physicalType: DECIMAL(8,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CVENDQ
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CFIL06
    logicalType: number
    description: None
    required: true
    physicalType: DECIMAL(10,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CFIL06
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CFIL07
    logicalType: number
    description: None
    required: true
    physicalType: DECIMAL(10,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CFIL07
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CFIL08
    logicalType: number
    description: None
    required: true
    physicalType: DECIMAL(8,2)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CFIL08
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CFIL09
    logicalType: number
    description: None
    required: true
    physicalType: DECIMAL(10,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CFIL09
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CFIL10
    logicalType: number
    description: None
    required: true
    physicalType: DECIMAL(10,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CFIL10
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CFIL11
    logicalType: number
    description: None
    required: true
    physicalType: DECIMAL(8,2)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CFIL11
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CCCTRA
    logicalType: string
    description: CODE DE CONTRAT C = CONTRAT NEGOCIE E = ENTENTE AV
    required: true
    physicalType: CHAR(1)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CCCTRA
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CCSURC
    logicalType: string
    description: CODE DE SURCHARGE A = SURCHARGE MEDIS AVANT LA SOU
    required: true
    physicalType: CHAR(1)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CCSURC
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMANDA
    logicalType: string
    description: MANDAT
    required: true
    physicalType: CHAR(12)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMANDA
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CFIL12
    logicalType: number
    description: None
    required: true
    physicalType: DECIMAL(8,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CFIL12
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CICTRP
    logicalType: string
    description: IND. CONTRAT PARTICULIER
    required: true
    physicalType: CHAR(1)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CICTRP
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CFIL13
    logicalType: number
    description: None
    required: true
    physicalType: DECIMAL(8,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CFIL13
    transformLogic: no transformation
    transformDescription: no transformation
  - name: COFFI
    logicalType: number
    description: '% REMISE'
    required: true
    physicalType: DECIMAL(8,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.COFFI
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CFIL14
    logicalType: number
    description: None
    required: true
    physicalType: DECIMAL(8,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CFIL14
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CFIL15
    logicalType: number
    description: None
    required: true
    physicalType: DECIMAL(8,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CFIL15
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CFIL16
    logicalType: number
    description: None
    required: true
    physicalType: DECIMAL(8,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CFIL16
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CFIL17
    logicalType: number
    description: None
    required: true
    physicalType: DECIMAL(8,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CFIL17
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CFIL18
    logicalType: number
    description: None
    required: true
    physicalType: DECIMAL(8,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CFIL18
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CFIL19
    logicalType: number
    description: None
    required: true
    physicalType: DECIMAL(8,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CFIL19
    transformLogic: no transformation
    transformDescription: no transformation
  - name: NMUTL
    logicalType: string
    description: CODE UTILISATEUR
    required: true
    physicalType: CHAR(10)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.NMUTL
    transformLogic: no transformation
    transformDescription: no transformation
  - name: DTDRNMAJ
    logicalType: date
    description: DATE DERNIERE MAJ
    required: true
    physicalType: DATE
    transformSourceObjects:
    - PMGENDTA.CTRANEG.DTDRNMAJ
    transformLogic: no transformation
    transformDescription: no transformation
  - name: DTCRT
    logicalType: date
    description: DATE CREATION
    required: true
    physicalType: DATE
    transformSourceObjects:
    - PMGENDTA.CTRANEG.DTCRT
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CFIL20
    logicalType: number
    description: MONTANT VENDANTS A DATE
    required: true
    physicalType: DECIMAL(9,2)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CFIL20
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMTAVT
    logicalType: number
    description: PRIX VENDANT AVANT TAXE
    required: true
    physicalType: DECIMAL(8,3)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMTAVT
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMTPRA
    logicalType: number
    description: COUTANT PRA
    required: true
    physicalType: DECIMAL(9,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMTPRA
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMTVRF
    logicalType: number
    description: VENDANT VALEUR DE RACHAT
    required: true
    physicalType: DECIMAL(9,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMTVRF
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMTBBA
    logicalType: number
    description: MONTANT BILL-BACK ACHAT
    required: true
    physicalType: DECIMAL(9,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMTBBA
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMTBBV
    logicalType: number
    description: MONTANT BILL-BACK VENTE
    required: true
    physicalType: DECIMAL(9,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMTBBV
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMTDPR
    logicalType: number
    description: DERNIER PRIX RECEPTION
    required: true
    physicalType: DECIMAL(9,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMTDPR
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMTCTR
    logicalType: number
    description: PRIX CONTRAT
    required: true
    physicalType: DECIMAL(9,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMTCTR
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMTCST
    logicalType: number
    description: COUT MCKESSON
    required: true
    physicalType: DECIMAL(9,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMTCST
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMTDFO
    logicalType: number
    description: DIFFÉRENCE REM. OFF INVOICE
    required: true
    physicalType: DECIMAL(9,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMTDFO
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMTDFV
    logicalType: number
    description: DIFFÉRENCE WAC BILL BCK VTE
    required: true
    physicalType: DECIMAL(9,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMTDFV
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMTPBA
    logicalType: number
    description: PRCENTAGE BILL BACK ACHAT
    required: true
    physicalType: DECIMAL(9,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMTPBA
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMTPBV
    logicalType: number
    description: PRCENTAGE BILL BACK VENTE
    required: true
    physicalType: DECIMAL(9,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMTPBV
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMTOFI
    logicalType: number
    description: MONTANT REMISE OFF INVOICE
    required: true
    physicalType: DECIMAL(9,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMTOFI
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMTPRD
    logicalType: number
    description: MONTANT PRA A DATE
    required: true
    physicalType: DECIMAL(12,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMTPRD
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMTPRM
    logicalType: number
    description: MONTANT PRA DU MOIS
    required: true
    physicalType: DECIMAL(12,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMTPRM
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMTVDS
    logicalType: number
    description: MONTANT VENDANTS DU MOIS
    required: true
    physicalType: DECIMAL(10,2)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMTVDS
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMTVFA
    logicalType: number
    description: MONTANT VR FACTURES A DATE
    required: true
    physicalType: DECIMAL(12,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMTVFA
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMTVFM
    logicalType: number
    description: MONTANT VR FACTURES DU MOIS
    required: true
    physicalType: DECIMAL(12,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMTVFM
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMTVND
    logicalType: number
    description: MONTANT VENDANTS A DATE
    required: true
    physicalType: DECIMAL(10,2)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMTVND
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CQRESC
    logicalType: number
    description: QTE RESERVÉE PAR LES CLIENTS
    required: true
    physicalType: DECIMAL(6,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CQRESC
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CQRALR
    logicalType: number
    description: QTE RESERVÉE À LIVRER EN RETENUE
    required: true
    physicalType: DECIMAL(6,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CQRALR
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CTCTR
    logicalType: string
    description: TYPE DE CONTRAT
    required: true
    physicalType: CHAR(1)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CTCTR
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CIEMPI
    logicalType: string
    description: INDC PERMETTRE EMPRUNT INVENTAIRE
    required: true
    physicalType: CHAR(1)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CIEMPI
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CIBOEC
    logicalType: string
    description: INDC BO ENREGISTRÉ SUR CONTRAT
    required: true
    physicalType: CHAR(1)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CIBOEC
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CIACHC
    logicalType: string
    description: INDC PERMETTRE ACHAT SUR CONTRAT
    required: true
    physicalType: CHAR(1)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CIACHC
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CICMPX
    logicalType: string
    description: INDC CONTRAT AU MEILLEUR PRIX VENDANT
    required: true
    physicalType: CHAR(1)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CICMPX
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CQPLAN
    logicalType: number
    description: QTE PLANIFIÉE POUR LA DURÉE DU CONTRAT
    required: true
    physicalType: DECIMAL(7,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CQPLAN
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CQMINC
    logicalType: number
    description: QTE SEUIL MINIMUM SOUS CONTRAT
    required: true
    physicalType: DECIMAL(6,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CQMINC
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CCPCRI
    logicalType: string
    description: CODE PRODUIT CRITIQUE
    required: true
    physicalType: CHAR(1)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CCPCRI
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CQFCNV
    logicalType: number
    description: FACTEUR DE CONVERSION
    required: true
    physicalType: DECIMAL(5,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CQFCNV
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CCSYMB
    logicalType: string
    description: SYMBOLE DE CONVERSION (/,*)
    required: true
    physicalType: CHAR(1)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CCSYMB
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMICTR
    logicalType: number
    description: PRIX CONTRAT INITIAL
    required: true
    physicalType: DECIMAL(9,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMICTR
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMICST
    logicalType: number
    description: COUT MCKESSON INITIAL
    required: true
    physicalType: DECIMAL(9,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMICST
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMIOFI
    logicalType: number
    description: MONTANT REMISE OFF INVOICE INITIAL
    required: true
    physicalType: DECIMAL(9,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMIOFI
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMIAVT
    logicalType: number
    description: PRIX VENDANT AVANT TAXE INITIAL
    required: true
    physicalType: DECIMAL(8,3)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMIAVT
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CQIPLN
    logicalType: number
    description: QTE PLANIFIÉE POUR LA DURÉE DU CONTRAT INITIALE
    required: true
    physicalType: DECIMAL(7,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CQIPLN
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CQIMIN
    logicalType: number
    description: QTE SEUIL MINIMUM SOUS CONTRAT INITIALE
    required: true
    physicalType: DECIMAL(6,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CQIMIN
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CCMCOM
    logicalType: string
    description: CODE MODÈLE D'ENGAGEMENT (COMMITMENT
    required: true
    physicalType: CHAR(1)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CCMCOM
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CNOPRX
    logicalType: number
    description: NUMÉRO DE CHANGEMENT DE PRIX
    required: true
    physicalType: NUMERIC(8,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CNOPRX
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CTYPACH
    logicalType: string
    description: TYPE ACHAT A = PRIX CONTRAT B = VR REG & BBV & REC
    required: true
    physicalType: CHAR(1)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CTYPACH
    transformLogic: no transformation
    transformDescription: no transformation
  - name: DTMAJVR
    logicalType: date
    description: DATE MISE À JOUR VR
    required: true
    physicalType: DATE
    transformSourceObjects:
    - PMGENDTA.CTRANEG.DTMAJVR
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMTSUB
    logicalType: number
    description: MONTANT DE SUBVENTION
    required: true
    physicalType: DECIMAL(9,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMTSUB
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CNPRDA
    logicalType: number
    description: NO PRODUIT ATTRIBUÉ MULTI-ATTRIBUTION
    required: true
    physicalType: DECIMAL(6,0)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CNPRDA
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMVNSF
    logicalType: number
    description: PRIX VENDANT SANS FRAIS
    required: true
    physicalType: DECIMAL(8,3)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMVNSF
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CMVRSF
    logicalType: number
    description: VR SANS FRAIS
    required: true
    physicalType: DECIMAL(9,4)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CMVRSF
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CIPXPR
    logicalType: string
    description: INDICATEUR PRIX PRIORITAIRE
    required: true
    physicalType: CHAR(1)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CIPXPR
    transformLogic: no transformation
    transformDescription: no transformation
  - name: CCBIPN
    logicalType: string
    description: CODE CHARGEBACK INTER-PROV
    required: true
    physicalType: CHAR(1)
    transformSourceObjects:
    - PMGENDTA.CTRANEG.CCBIPN
    transformLogic: no transformation
    transformDescription: no transformation
```
